export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';

export const FETCH_STARSHIPS = 'FETCH_STARSHIPS';
export const SEARCH_STARSHIP = 'SEARCH_STARSHIP';

export const FETCH_PLANETS = 'FETCH_PLANETS';
export const SEARCH_PLANET = 'SEARCH_PLANET';